apiVersion: v1
kind: Pod
metadata:
  name: ascend310p-job
spec:
  containers:
    - name: ubuntu-container
      image: swr.cn-south-1.myhuaweicloud.com/ascendhub/ascend-pytorch:24.0.RC1-A2-1.11.0-ubuntu20.04
      command: ["bash", "-c", "sleep 86400"]
      resources:
        limits:
          huawei.com/Ascend310P: 1 # requesting 1 NPU
          huawei.com/Ascend310P-memory: 2000 # requesting 2000m device m